name: Deploy Notification Service Container App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'apps/notify-service/notify/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # ── STEP 1 - Downloads repository code onto the Linux machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ── STEP 2 - Installs Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # ── STEP 3 - Cache SonarCloud packages
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # ── STEP 4 - Cache Maven packages (speeds up future builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # ── STEP 5 - Compiles code, creates .jar file AND runs SonarCloud scan
      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -DskipTests
          -Dsonar.projectKey=pamali-ranasinghe_notify-service
          -Dsonar.organization=pamali-ranasinghe
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: apps/notify-service/notify

      # ── STEP 6 - Logs in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NOTIFY_DOCKER_USERNAME }}
          password: ${{ secrets.NOTIFY_DOCKER_PASSWORD }}

      # ── STEP 7 - Builds a Docker image from your Dockerfile
      - name: Build Docker image
        run: docker build -t ${{ secrets.NOTIFY_DOCKER_USERNAME }}/notify-service:latest .
        working-directory: apps/notify-service/notify

      # ── STEP 8 - Uploads (pushes) the Docker image to Docker Hub and Azure pulls it during deployment
      - name: Push to Docker Hub
        run: docker push ${{ secrets.NOTIFY_DOCKER_USERNAME }}/notify-service:latest

      # ── STEP 9 - Logs in to your Azure account
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NOTIFY_AZURE_CREDENTIALS }}

      # ── STEP 10 - Azure Container Apps to pull the new Docker image and restart your app
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name notification-service \
            --resource-group pamalis-group \
            --image ${{ secrets.NOTIFY_DOCKER_USERNAME }}/notify-service:latest
